export type Language = 'cs' | 'en';
export const english: Record<string,string> = {
 'Technický slovník':'Technical vocabulary','Moje slovíčka z praxe':'My vocabulary from work','Přidat slovíčko':'Add a word','Najít nové slovíčko':'Find a new word','Anglicko-japonský slovník Jisho':'English–Japanese dictionary · Jisho','Anglický nebo japonský výraz':'English or Japanese word','Např. voltage, bearing, fan…':'E.g. voltage, bearing, fan…','Hledám…':'Searching…','Vyhledat':'Search','Otevřít Jisho':'Open Jisho','Žádný výsledek. Zkus kratší výraz nebo jiné anglické slovo.':'No results. Try a shorter term or another English word.','Detail na Jisho':'Details on Jisho','Použít':'Use','Můj slovník':'My vocabulary','Načítání…':'Loading…','Klikni na název a otevři popis nebo vlastní fotku.':'Select a word to view its description and photo.','Zkusit znovu':'Try again','Česky':'Czech','Anglicky':'English','Japonsky':'Japanese','rómadži':'romaji','Akce':'Actions','Slovník je prázdný. Přidej své první slovíčko.':'Your vocabulary is empty. Add your first word.','Dlouhá samohláska: ū = uu, ō = ou, ē = ee.':'Long vowels: ū = uu, ō = ou, ē = ee.','Nové slovíčko':'New word','Přidej názvy ve všech třech jazycích.':'Enter the word in all three languages.','Japonsky v rómadži':'Japanese in romaji','Stručný popis':'Short description','(volitelné)':'(optional)','Ukládám…':'Saving…','Uložit slovíčko':'Save word','Japonsky · rómadži':'Japanese · romaji','K tomuto slovíčku zatím není popis.':'No description yet.','Přidej fotku z práce nebo vlastní obrázek.':'Add a photo from work or your own image.','Přidat obrázek':'Add image','Vyfotit':'Take photo','JPG, PNG, WebP nebo GIF · do 8 MB. Fotoaparát podle podpory zařízení.':'JPG, PNG, WebP or GIF · up to 8 MB. Camera depends on your device.','Ukládám fotku…':'Saving photo…','Slovíčko bude odebráno ze slovníku.':'This word will be removed from your vocabulary.','Zrušit':'Cancel','Mažu…':'Deleting…','Smazat':'Delete','Fotka':'Photo','Slovíčko přidáno.':'Word added.','Slovíčko smazáno.':'Word deleted.','Fotka uložena.':'Photo saved.','Hledat v mém slovníku':'Search my vocabulary','Hledej japonsky, anglicky nebo česky…':'Search Japanese, English or Czech…','Nic nenalezeno. Zkus jiný výraz.':'No matches. Try another term.','Vymazat hledání':'Clear search','Poslechnout':'Listen','Zavřít':'Close','Poslech japonštiny není v tomto prohlížeči dostupný.':'Japanese speech is not available in this browser.','Japonský hlas není dostupný. Zkus Safari nebo zapni japonský hlas v zařízení.':'No Japanese voice is available. Try Safari or enable a Japanese voice on your device.','Výslovnost se nepodařilo přehrát. Zkus to znovu.':'Pronunciation could not be played. Please try again.',
 'Operace se nezdařila.':'The operation failed.','Slovník se nepodařilo načíst. Zkus to znovu.':'Could not load your vocabulary. Please try again.','Vyplň všechny tři názvy (nejvýše 200 znaků).':'Enter all three names (up to 200 characters each).','Popis může mít nejvýše 3000 znaků.':'The description can contain up to 3000 characters.','Neplatné slovíčko.':'Invalid word.','Slovíčko se nepodařilo uložit.':'Could not save the word.','Chybí slovíčko.':'Missing word.','Slovíčko se nepodařilo smazat.':'Could not delete the word.','Vyber JPG, PNG, WebP nebo GIF do 8 MB.':'Choose JPG, PNG, WebP or GIF up to 8 MB.','Slovíčko už neexistuje.':'This word no longer exists.','Fotku se nepodařilo uložit. Zkus to znovu.':'Could not save the photo. Please try again.','Zadej výraz do 100 znaků.':'Enter a term up to 100 characters.','Online slovník teď neodpovídá. Zkus hledání znovu nebo otevři Jisho.':'The online dictionary is unavailable. Retry or open Jisho.'
};
export function translate(language:Language,text:string){return language==='en'?(english[text]??text):text;}
export const englishDescriptions:Record<string,string> = {
 voltage:'Voltage is the difference in electric potential. Unit: volt (V). Fan tests include supply voltage and starting voltage.',
 current:'Electric current is the flow of electric charge. Unit: ampere (A), often milliampere (mA). For a fan, this is the current it draws.',
 speed:'The rotational speed of the rotor, usually given in revolutions per minute: rpm or r/min. General speed is sokudo in Japanese.',
 measurement:'Determining the value of a quantity using a measuring instrument. Fan measurements include voltage, current, rotational speed and noise.',
 'power-supply':'A source of electrical power. A laboratory power supply allows you to set the voltage and usually limit the current.',
 tachometer:'An instrument for measuring rotational speed. An optical tachometer typically detects a reflection from a mark on the rotating part. Another Japanese term is takomētā.',
 multimeter:'An instrument with several measurement functions, such as voltage, current and resistance. Select the correct function and lead sockets for each measurement.',
 connection:'Joining wires, instruments or components. In electrical testing, this includes connecting a fan to a power supply.',
 pq:'A curve showing the relationship between fan airflow Q and static pressure P. It shows how airflow changes as resistance to airflow varies.',
 noise:'Sound produced by a fan. Its level is often stated in dB(A). Electrical noise is a different meaning of noise and is called noizu in Japanese.'
};
