'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {BookOpen,Plus,Trash2,Camera,ImagePlus} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import type {Word} from '@/lib/words';
import type {DictionaryResult} from '@/lib/dictionary';
const blank={cs:'',en:'',ja:'',description:''};
async function api(path:string,options?:RequestInit){const r=await fetch(path,options);const data:any=await r.json();if(!r.ok)throw Error(data.error??'Operace se nezdařila.');return data;}
export default function Home(){
const [words,setWords]=useState<Word[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[add,setAdd]=useState(false),[selected,setSelected]=useState<Word|null>(null),[deleting,setDeleting]=useState<Word|null>(null),[draft,setDraft]=useState(blank),[notice,setNotice]=useState('');
const [query,setQuery]=useState(''),[results,setResults]=useState<DictionaryResult[]>([]),[searching,setSearching]=useState(false),[searched,setSearched]=useState(false),[searchError,setSearchError]=useState('');
const file=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null);
const load=useCallback(async()=>{setLoading(true);setError('');try{setWords(await api('/api/words'));}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
useEffect(()=>{void load();},[load]);
const create=useCallback(async(input:typeof blank)=>{const word=await api('/api/words',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});setWords(w=>[...w,word]);return word;},[]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const c=new AbortController();const register=(tool:any)=>{try{Promise.resolve(context.registerTool(tool,{signal:c.signal})).catch(console.error);}catch(e){console.error(e);}};register({name:'list_vocabulary',description:'Read the saved Czech, English and Japanese romanized vocabulary.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>api('/api/words')});register({name:'add_vocabulary',description:'Save a vocabulary entry and update the visible dictionary.',inputSchema:{type:'object',properties:{cs:{type:'string'},en:{type:'string'},ja:{type:'string'},description:{type:'string'}},required:['cs','en','ja'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(p:any)=>{if(!p||['cs','en','ja'].some(k=>typeof p[k]!=='string'||!p[k].trim()))throw Error('All three names are required');return create({...p,description:p.description??''});}});return()=>c.abort();},[create]);
async function search(e:React.FormEvent){e.preventDefault();setSearching(true);setSearchError('');setResults([]);setSearched(false);try{const data=await api('/api/dictionary?q='+encodeURIComponent(query));setResults(data.results);setSearched(true);}catch(e){setSearchError((e as Error).message);}finally{setSearching(false);}}
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await create(draft);setDraft(blank);setAdd(false);setNotice('Slovíčko přidáno.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
async function remove(){if(!deleting)return;setBusy(true);setError('');try{await api(`/api/words?id=${encodeURIComponent(deleting.id)}`,{method:'DELETE'});setWords(w=>w.filter(x=>x.id!==deleting.id));if(selected?.id===deleting.id)setSelected(null);setDeleting(null);setNotice('Slovíčko smazáno.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
async function upload(image?:File){if(!image||!selected)return;setBusy(true);setError('');try{const form=new FormData();form.append('id',selected.id);form.append('image',image);const result=await api('/api/words/image',{method:'POST',body:form});const updated={...selected,imageKey:result.imageKey};setSelected(updated);setWords(w=>w.map(x=>x.id===updated.id?updated:x));setNotice('Fotka uložena.');}catch(e){setError((e as Error).message);}finally{setBusy(false);if(file.current)file.current.value='';if(camera.current)camera.current.value='';}}
return <main className="workspace"><header className="top"><div className="brand"><span className="brand-icon"><BookOpen size={25}/></span><div><h1>Technický slovník</h1><p>Moje slovíčka z praxe</p></div></div><Button onClick={()=>{setError('');setAdd(true);}} className="add-button"><Plus size={19}/>Přidat slovíčko</Button></header>
<section className="lookup" aria-labelledby="lookup-heading"><div><h2 id="lookup-heading">Najít nové slovíčko</h2><p>Anglicko-japonský slovník Jisho</p></div><form onSubmit={search}><label className="sr-only" htmlFor="dictionary-query">Anglický nebo japonský výraz</label><Input id="dictionary-query" placeholder="Např. voltage, bearing, fan…" value={query} maxLength={100} onChange={e=>setQuery(e.target.value)} required/><Button disabled={searching}>{searching?'Hledám…':'Vyhledat'}</Button></form>
{searchError&&<p role="alert" className="error">{searchError} <a href={'https://jisho.org/search/'+encodeURIComponent(query)} target="_blank" rel="noreferrer">Otevřít Jisho</a></p>}
{searched&&results.length===0&&<p role="status">Žádný výsledek. Zkus kratší výraz nebo jiné anglické slovo.</p>}
{!!results.length&&<div className="results">{results.map((r,i)=><article key={r.word+i}><div><strong>{r.romaji}</strong><span lang="ja">{r.word} · {r.reading}</span><p>{r.meanings.join('; ')}</p><a href={r.url} target="_blank" rel="noreferrer">Detail na Jisho</a></div><Button variant="outline" onClick={()=>{setDraft({cs:'',en:r.meanings[0]??query,ja:r.romaji,description:'Význam (EN): '+r.meanings.join('; ')});setError('');setAdd(true);}}>Použít</Button></article>)}<p className="source">Významy: Jisho / JMdict · <a href="https://www.edrdg.org/edrdg/licence.html" target="_blank" rel="noreferrer">EDRDG, CC BY-SA</a>. Vyber význam podle kontextu. Český název doplníš před uložením.</p></div>}
</section><section className="dictionary"><div className="section-title"><h2>Můj slovník</h2><span>{loading?'Načítání…':`${words.length} slovíček`}</span></div><p className="hint">Klikni na název a otevři popis nebo vlastní fotku.</p>
{error&&!add&&!selected&&!deleting&&<div role="alert" className="error">{error} <Button variant="outline" onClick={load}>Zkusit znovu</Button></div>}
<Table className="word-table"><TableHeader><TableRow><TableHead>Česky</TableHead><TableHead>Anglicky</TableHead><TableHead>Japonsky <span className="romaji">rómadži</span></TableHead><TableHead><span className="sr-only">Akce</span></TableHead></TableRow></TableHeader><TableBody>{words.map((w,i)=><TableRow key={w.id}><TableCell><button className="word-link" onClick={()=>{setError('');setSelected(w);}}><span className="number">{String(i+1).padStart(2,'0')}</span>{w.cs}</button></TableCell><TableCell><button className="plain-word" onClick={()=>{setError('');setSelected(w);}}>{w.en}</button></TableCell><TableCell><button className="plain-word japanese" onClick={()=>{setError('');setSelected(w);}}>{w.ja}</button></TableCell><TableCell><Button variant="ghost" size="icon" aria-label={`Smazat ${w.cs}`} onClick={()=>{setError('');setDeleting(w);}}><Trash2 size={17}/></Button></TableCell></TableRow>)}</TableBody></Table>
{!loading&&!error&&!words.length&&<p className="empty">Slovník je prázdný. Přidej své první slovíčko.</p>}
</section><footer><span>ČEŠTINA · ENGLISH · RŌMAJI</span><p>Dlouhá samohláska: ū = uu, ō = ou, ē = ee.</p></footer><p className="sr-only" role="status">{notice}</p>
<Dialog open={add} onOpenChange={v=>{if(!busy)setAdd(v);}}><DialogContent className="detail"><DialogHeader><DialogTitle>Nové slovíčko</DialogTitle><DialogDescription>Přidej názvy ve všech třech jazycích.</DialogDescription></DialogHeader><form onSubmit={submit} className="form">{(['cs','en','ja'] as const).map((k,i)=><label key={k}>{['Česky','Anglicky','Japonsky v rómadži'][i]}<Input required maxLength={200} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<label>Stručný popis <span>(volitelné)</span><textarea maxLength={3000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>{error&&<p role="alert" className="error">{error}</p>}<Button disabled={busy} type="submit">{busy?'Ukládám…':'Uložit slovíčko'}</Button></form></DialogContent></Dialog>
<Dialog open={!!selected} onOpenChange={v=>{if(!v&&!busy)setSelected(null);}}><DialogContent className="detail"><DialogHeader><DialogTitle>{selected?.cs}</DialogTitle><DialogDescription>{selected?.en}</DialogDescription></DialogHeader>{selected&&<><div className="romaji-card"><span>Japonsky · rómadži</span><strong>{selected.ja}</strong></div><p className="definition">{selected.description||'K tomuto slovíčku zatím není popis.'}</p>{selected.imageKey?<img className="photo" alt={`Fotka: ${selected.cs}`} src={`/api/words/image?id=${encodeURIComponent(selected.id)}&v=${encodeURIComponent(selected.imageKey)}`}/>:<div className="photo-empty"><ImagePlus size={28}/><p>Přidej fotku z práce nebo vlastní obrázek.</p></div>}<div className="photo-buttons"><Button variant="outline" disabled={busy} onClick={()=>file.current?.click()}><ImagePlus size={18}/>Přidat obrázek</Button><Button variant="outline" disabled={busy} onClick={()=>camera.current?.click()}><Camera size={18}/>Vyfotit</Button></div><input ref={file} hidden type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>void upload(e.target.files?.[0])}/><input ref={camera} hidden type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>void upload(e.target.files?.[0])}/><p className="file-hint">JPG, PNG, WebP nebo GIF · do 8 MB. Fotoaparát podle podpory zařízení.</p>{busy&&<p role="status">Ukládám fotku…</p>}{error&&<p role="alert" className="error">{error}</p>}</>}</DialogContent></Dialog>
<AlertDialog open={!!deleting} onOpenChange={v=>{if(!v&&!busy)setDeleting(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Smazat „{deleting?.cs}“?</AlertDialogTitle><AlertDialogDescription>Slovíčko bude odebráno ze slovníku.</AlertDialogDescription></AlertDialogHeader>{error&&<p role="alert" className="error">{error}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>Zrušit</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void remove();}}>{busy?'Mažu…':'Smazat'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
</main>;
}
