'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import {BookOpen,Plus,Trash2,Camera,ImagePlus,Volume2,Search} from 'lucide-react';
import {toHiragana} from 'wanakana';
import {translate,englishDescriptions,type Language} from '@/lib/language';
import {pronunciationText,normalizeSearch} from '@/lib/pronunciation';
import {initialWords} from '@/lib/words';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableHeader,TableBody,TableRow,TableHead,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import type {Word} from '@/lib/words';
import type {DictionaryResult} from '@/lib/dictionary';
const blank={cs:'',en:'',ja:'',description:''};
async function api(path:string,options?:RequestInit){const r=await fetch(path,options);const data:any=await r.json();if(!r.ok)throw Error(data.error??'Operace se nezdařila.');return data;}
export default function Home(){
const [language,setLanguage]=useState<Language>('cs'),[filter,setFilter]=useState(''),[speechError,setSpeechError]=useState('');
const utterance=useRef<SpeechSynthesisUtterance|null>(null);
const t=(text:string)=>translate(language,text);
useEffect(()=>{try{if(localStorage.getItem('vocabulary-language')==='en')setLanguage('en');}catch{}return()=>{if(typeof window!=='undefined'&&'speechSynthesis' in window)window.speechSynthesis.cancel();};},[]);
useEffect(()=>{document.documentElement.lang=language;document.title=t('Technický slovník');try{localStorage.setItem('vocabulary-language',language);}catch{}},[language]);
function speak(romaji:string,id?:string,kana?:string){setSpeechError('');if(!('speechSynthesis' in window)){setSpeechError('Poslech japonštiny není v tomto prohlížeči dostupný.');return;}const synth=window.speechSynthesis;const voices=synth.getVoices();const voice=voices.find(v=>v.lang.toLowerCase().startsWith('ja'));if(voices.length&&!voice){setSpeechError('Japonský hlas není dostupný. Zkus Safari nebo zapni japonský hlas v zařízení.');return;}synth.cancel();const speech=new SpeechSynthesisUtterance(kana??pronunciationText(romaji,id));speech.lang='ja-JP';speech.rate=.85;if(voice)speech.voice=voice;speech.onerror=e=>{if(e.error!=='canceled'&&e.error!=='interrupted')setSpeechError('Výslovnost se nepodařilo přehrát. Zkus to znovu.');};utterance.current=speech;synth.speak(speech);}
const [words,setWords]=useState<Word[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(false),[add,setAdd]=useState(false),[selected,setSelected]=useState<Word|null>(null),[deleting,setDeleting]=useState<Word|null>(null),[draft,setDraft]=useState(blank),[notice,setNotice]=useState('');
const [query,setQuery]=useState(''),[results,setResults]=useState<DictionaryResult[]>([]),[searching,setSearching]=useState(false),[searched,setSearched]=useState(false),[searchError,setSearchError]=useState('');
const file=useRef<HTMLInputElement>(null),camera=useRef<HTMLInputElement>(null);
const load=useCallback(async()=>{setLoading(true);setError('');try{setWords(await api('/api/words'));}catch(e){setError((e as Error).message);}finally{setLoading(false);}},[]);
useEffect(()=>{void load();},[load]);
const create=useCallback(async(input:typeof blank)=>{const word=await api('/api/words',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(input)});setWords(w=>[...w,word]);return word;},[]);
useEffect(()=>{const context=(document as any).modelContext;if(!context?.registerTool)return;const c=new AbortController();const register=(tool:any)=>{try{Promise.resolve(context.registerTool(tool,{signal:c.signal})).catch(console.error);}catch(e){console.error(e);}};register({name:'list_vocabulary',description:'Read the saved Czech, English and Japanese romanized vocabulary.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:async()=>api('/api/words')});register({name:'add_vocabulary',description:'Save a vocabulary entry and update the visible dictionary.',inputSchema:{type:'object',properties:{cs:{type:'string'},en:{type:'string'},ja:{type:'string'},description:{type:'string'}},required:['cs','en','ja'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(p:any)=>{if(!p||['cs','en','ja'].some(k=>typeof p[k]!=='string'||!p[k].trim()))throw Error('All three names are required');return create({...p,description:p.description??''});}});return()=>c.abort();},[create]);
async function search(e:React.FormEvent){e.preventDefault();setSearching(true);setSearchError('');setResults([]);setSearched(false);try{const data=await api('/api/dictionary?q='+encodeURIComponent(query));setResults(data.results);setSearched(true);}catch(e){setSearchError((e as Error).message);}finally{setSearching(false);}}
async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await create(draft);setDraft(blank);setAdd(false);setNotice('Slovíčko přidáno.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
async function remove(){if(!deleting)return;setBusy(true);setError('');try{await api(`/api/words?id=${encodeURIComponent(deleting.id)}`,{method:'DELETE'});setWords(w=>w.filter(x=>x.id!==deleting.id));if(selected?.id===deleting.id)setSelected(null);setDeleting(null);setNotice('Slovíčko smazáno.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
async function upload(image?:File){if(!image||!selected)return;setBusy(true);setError('');try{const form=new FormData();form.append('id',selected.id);form.append('image',image);const result=await api('/api/words/image',{method:'POST',body:form});const updated={...selected,imageKey:result.imageKey};setSelected(updated);setWords(w=>w.map(x=>x.id===updated.id?updated:x));setNotice('Fotka uložena.');}catch(e){setError((e as Error).message);}finally{setBusy(false);if(file.current)file.current.value='';if(camera.current)camera.current.value='';}}
const searchTerm=normalizeSearch(filter);
const visibleWords=words.filter(w=>[w.ja,w.en,w.cs,toHiragana(pronunciationText(w.ja,w.id))].some(v=>normalizeSearch(v).includes(searchTerm)));
const description=selected&&language==='en'&&selected.description===initialWords.find(w=>w.id===selected.id)?.description?englishDescriptions[selected.id]:selected?.description;
return <main className="workspace"><header className="top"><div className="brand"><span className="brand-icon"><BookOpen size={25}/></span><div><h1>{t('Technický slovník')}</h1><p>{t('Moje slovíčka z praxe')}</p></div></div><div className="header-actions"><div className="language-switch" aria-label="Language"><Button variant={language==='cs'?'default':'ghost'} aria-pressed={language==='cs'} onClick={()=>setLanguage('cs')}>Česky</Button><Button variant={language==='en'?'default':'ghost'} aria-pressed={language==='en'} onClick={()=>setLanguage('en')}>English</Button></div><Button onClick={()=>{setError('');setAdd(true);}} className="add-button"><Plus size={19}/>{t('Přidat slovíčko')}</Button></div></header>
<section className="dictionary"><div className="section-title"><h2>{t('Můj slovník')}</h2><span>{loading?t('Načítání…'):`${visibleWords.length}${searchTerm?' / '+words.length:''} ${language==='en'?'words':'slovíček'}`}</span></div><div className="saved-search"><label htmlFor="saved-search"><Search size={18}/>{t('Hledat v mém slovníku')}</label><div><Input id="saved-search" type="search" placeholder={t('Hledej japonsky, anglicky nebo česky…')} value={filter} onChange={e=>setFilter(e.target.value)}/>{filter&&<Button variant="ghost" onClick={()=>setFilter('')}>{t('Vymazat hledání')}</Button>}</div></div><p className="hint">{t('Klikni na název a otevři popis nebo vlastní fotku.')}</p>
{error&&!add&&!selected&&!deleting&&<div role="alert" className="error">{t(error)} <Button variant="outline" onClick={load}>{t('Zkusit znovu')}</Button></div>}
{speechError&&<p role="alert" className="error">{t(speechError)}</p>}
<Table className="word-table"><TableHeader><TableRow><TableHead>{t('Japonsky')} <span className="romaji">{t('rómadži')}</span></TableHead><TableHead>{t('Anglicky')}</TableHead><TableHead>{t('Česky')}</TableHead><TableHead><span className="sr-only">{t('Akce')}</span></TableHead></TableRow></TableHeader><TableBody>{visibleWords.map((w,i)=><TableRow key={w.id}><TableCell><div className="japanese-word"><button className="word-link japanese" onClick={()=>{setError('');setSelected(w);}}><span className="number">{String(i+1).padStart(2,'0')}</span>{w.ja}</button><Button variant="ghost" size="icon" aria-label={`${t('Poslechnout')}: ${w.ja}`} onClick={()=>speak(w.ja,w.id)}><Volume2 size={18}/></Button></div></TableCell><TableCell><button className="plain-word" onClick={()=>{setError('');setSelected(w);}}>{w.en}</button></TableCell><TableCell><button className="plain-word" onClick={()=>{setError('');setSelected(w);}}>{w.cs}</button></TableCell><TableCell><Button variant="ghost" size="icon" aria-label={`${t('Smazat')} ${w.ja}`} onClick={()=>{setError('');setDeleting(w);}}><Trash2 size={17}/></Button></TableCell></TableRow>)}</TableBody></Table>
{!loading&&!error&&!words.length&&<p className="empty">{t('Slovník je prázdný. Přidej své první slovíčko.')}</p>}{!loading&&words.length>0&&!visibleWords.length&&<p className="empty" role="status">{t('Nic nenalezeno. Zkus jiný výraz.')}</p>}
</section>
<section className="lookup" aria-labelledby="lookup-heading"><div><h2 id="lookup-heading">{t('Najít nové slovíčko')}</h2><p>{t('Anglicko-japonský slovník Jisho')}</p></div><form onSubmit={search}><label className="sr-only" htmlFor="dictionary-query">{t('Anglický nebo japonský výraz')}</label><Input id="dictionary-query" placeholder={t('Např. voltage, bearing, fan…')} value={query} maxLength={100} onChange={e=>setQuery(e.target.value)} required/><Button disabled={searching}>{t(searching?'Hledám…':'Vyhledat')}</Button></form>
{searchError&&<p role="alert" className="error">{t(searchError)} <a href={'https://jisho.org/search/'+encodeURIComponent(query)} target="_blank" rel="noreferrer">{t('Otevřít Jisho')}</a></p>}
{searched&&results.length===0&&<p role="status">{t('Žádný výsledek. Zkus kratší výraz nebo jiné anglické slovo.')}</p>}
{!!results.length&&<div className="results">{results.map((r,i)=><article key={r.word+i}><div><strong>{r.romaji}</strong><Button variant="ghost" size="icon" aria-label={`${t('Poslechnout')}: ${r.romaji}`} onClick={()=>speak(r.romaji,undefined,r.reading)}><Volume2 size={18}/></Button><span lang="ja">{r.word} · {r.reading}</span><p>{r.meanings.join('; ')}</p><a href={r.url} target="_blank" rel="noreferrer">{t('Detail na Jisho')}</a></div><Button variant="outline" onClick={()=>{setDraft({cs:'',en:r.meanings[0]??query,ja:r.romaji,description:'Meaning (EN): '+r.meanings.join('; ')});setError('');setAdd(true);}}>{t('Použít')}</Button></article>)}<p className="source">Jisho / JMdict · <a href="https://www.edrdg.org/edrdg/licence.html" target="_blank" rel="noreferrer">EDRDG, CC BY-SA</a>. {language==='en'?'Select the meaning that fits your context. Enter the Czech word before saving.':'Vyber význam podle kontextu. Český název doplníš před uložením.'}</p></div>}
</section><footer><span>RŌMAJI · ENGLISH · {language==='en'?'CZECH':'ČEŠTINA'}</span><p>{t('Dlouhá samohláska: ū = uu, ō = ou, ē = ee.')}</p></footer><p className="sr-only" role="status">{t(notice)}</p>
<Dialog open={add} onOpenChange={v=>{if(!busy)setAdd(v);}}><DialogContent className="detail" showCloseButton={false}><DialogHeader><DialogTitle>{t('Nové slovíčko')}</DialogTitle><DialogDescription>{t('Přidej názvy ve všech třech jazycích.')}</DialogDescription></DialogHeader><Button variant="ghost" className="close-dialog" aria-label={t('Zavřít')} disabled={busy} onClick={()=>setAdd(false)}>×</Button><form onSubmit={submit} className="form">{(['ja','en','cs'] as const).map((k,i)=><label key={k}>{t(['Japonsky v rómadži','Anglicky','Česky'][i])}<Input required maxLength={200} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/></label>)}<label>{t('Stručný popis')} <span>{t('(volitelné)')}</span><textarea maxLength={3000} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>{error&&<p role="alert" className="error">{t(error)}</p>}<Button disabled={busy} type="submit">{t(busy?'Ukládám…':'Uložit slovíčko')}</Button></form></DialogContent></Dialog>
<Dialog open={!!selected} onOpenChange={v=>{if(!v&&!busy)setSelected(null);}}><DialogContent className="detail" showCloseButton={false}><DialogHeader><DialogTitle>{selected?.ja}</DialogTitle><DialogDescription>{selected?.en} · {selected?.cs}</DialogDescription></DialogHeader><Button variant="ghost" className="close-dialog" aria-label={t('Zavřít')} disabled={busy} onClick={()=>setSelected(null)}>×</Button>{selected&&<><div className="romaji-card"><span>{t('Japonsky · rómadži')}</span><div className="pronunciation-line"><strong>{selected.ja}</strong><Button variant="outline" onClick={()=>speak(selected.ja,selected.id)}><Volume2 size={18}/>{t('Poslechnout')}</Button></div></div>{speechError&&<p role="alert" className="error">{t(speechError)}</p>}<p className="definition">{description||t('K tomuto slovíčku zatím není popis.')}</p>{selected.imageKey?<img className="photo" alt={`${t('Fotka')}: ${selected.ja}`} src={`/api/words/image?id=${encodeURIComponent(selected.id)}&v=${encodeURIComponent(selected.imageKey)}`}/>:<div className="photo-empty"><ImagePlus size={28}/><p>{t('Přidej fotku z práce nebo vlastní obrázek.')}</p></div>}<div className="photo-buttons"><Button variant="outline" disabled={busy} onClick={()=>file.current?.click()}><ImagePlus size={18}/>{t('Přidat obrázek')}</Button><Button variant="outline" disabled={busy} onClick={()=>camera.current?.click()}><Camera size={18}/>{t('Vyfotit')}</Button></div><input ref={file} hidden type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={e=>void upload(e.target.files?.[0])}/><input ref={camera} hidden type="file" accept="image/jpeg,image/png,image/webp" capture="environment" onChange={e=>void upload(e.target.files?.[0])}/><p className="file-hint">{t('JPG, PNG, WebP nebo GIF · do 8 MB. Fotoaparát podle podpory zařízení.')}</p>{busy&&<p role="status">{t('Ukládám fotku…')}</p>}{error&&<p role="alert" className="error">{t(error)}</p>}</>}</DialogContent></Dialog>
<AlertDialog open={!!deleting} onOpenChange={v=>{if(!v&&!busy)setDeleting(null);}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>{t('Smazat')} „{deleting?.ja}“?</AlertDialogTitle><AlertDialogDescription>{t('Slovíčko bude odebráno ze slovníku.')}</AlertDialogDescription></AlertDialogHeader>{error&&<p role="alert" className="error">{t(error)}</p>}<AlertDialogFooter><AlertDialogCancel disabled={busy}>{t('Zrušit')}</AlertDialogCancel><AlertDialogAction disabled={busy} onClick={e=>{e.preventDefault();void remove();}}>{t(busy?'Mažu…':'Smazat')}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
</main>;
}
